version: '3.8'

services:
  app:
    image: anujonline/host-chat:1.0
    build: .

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PUBLIC_KEY={VAPID_PUBLIC_KEY)
      - PRIVATE_KEY={VAPID_PRIVATE_KEY}
      - SUBJECT={VAPID_SUBJECT}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: